version: '2'

services:
    php56:
        image: bitnami/php-fpm:5.6
        container_name: pam4sdk-testphp56
        volumes:
            - .:/app
            - ./dockers/unittest/php56:/bitnami/php-fpm
    php70:
        image: bitnami/php-fpm:7.0
        container_name: pam4sdk-testphp70
        volumes:
            - .:/app
            - ./dockers/unittest/php70:/bitnami/php-fpm